files:
  - source: /res/values/*
    ignore:
      - dimens
      - '*attr*'
      - color
      - config
    translation: /res/values-%two_letters_code%/%original_file_name%
    translate_attributes: '0'
