files:
  - source: /res/values/
    ignore:
      - '*dimens*'
      - '*attrs*'
      - '*config*'
      - '*array*'
      - '*colors*'
translation: /res/values-%two_letters_code%/%original_file_name%
